import { VenueDietaryAttributes } from "@/domain/dietary/rules";
import { openStreetMapVenueUrl } from "@/providers/open-map";

export interface CuratedSingaporeVenue {
  id: string;
  name: string;
  address: string;
  coarseArea: string; // e.g. "Telok Ayer", "Bugis", "Tiong Bahru", "Orchard"
  cluster: "central_cbd" | "bugis_arab_st" | "orchard_somerset" | "tiong_bahru" | "holland_v" | "joo_chiat" | "dempsey" | "clarke_quay" | "novena";
  lat: number;
  lng: number;
  cuisine: string;
  cuisineCodes: string[];
  priceTier: 1 | 2 | 3 | 4;
  rating: number;
  ratingCount: number;
  dietary: VenueDietaryAttributes;
  supportedMealTypes: ("brunch" | "coffee" | "lunch" | "dinner" | "drinks")[];
  highlights: string[];
  bookingUrl: string;
  mapsUrl: string;
}

export const SINGAPORE_VENUES: CuratedSingaporeVenue[] = [
  {
    id: "sg-venue-01",
    name: "Dumpling Darlings",
    address: "44 Amoy Street, Singapore 069870",
    coarseArea: "Telok Ayer (CBD)",
    cluster: "central_cbd",
    lat: 1.2808,
    lng: 103.8475,
    cuisine: "Modern Asian & Craft Noodles",
    cuisineCodes: ["asian", "noodles", "chinese", "casual"],
    priceTier: 2,
    rating: 4.6,
    ratingCount: 1420,
    dietary: {
      hasVegetarianOptions: true,
      hasVeganOptions: true,
      hasNutFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["lunch", "dinner", "drinks"],
    highlights: ["Momo dumplings", "Smoked duck noodles", "Craft beers on tap"],
    bookingUrl: "https://www.dumplingdarlings.com.sg/reservations",
    mapsUrl: openStreetMapVenueUrl(1.2808, 103.8475),
  },
  {
    id: "sg-venue-02",
    name: "Tipo Pasta Bar",
    address: "28 Aliwal Street, Singapore 199918",
    coarseArea: "Bugis / Kampong Glam",
    cluster: "bugis_arab_st",
    lat: 1.3032,
    lng: 103.8596,
    cuisine: "Handmade Artisanal Pasta",
    cuisineCodes: ["italian", "pasta", "halal"],
    priceTier: 2,
    rating: 4.7,
    ratingCount: 2890,
    dietary: {
      isHalalCertified: true,
      isMuslimOwned: true,
      hasVegetarianOptions: true,
      isPorkFree: true,
      hasNutFreeOptions: true,
    },
    supportedMealTypes: ["lunch", "dinner"],
    highlights: ["Freshly extruded daily pasta", "Duck ragu", "Halal-certified bistro"],
    bookingUrl: "https://www.tipo.sg",
    mapsUrl: openStreetMapVenueUrl(1.3032, 103.8596),
  },
  {
    id: "sg-venue-03",
    name: "Merci Marcel Tiong Bahru",
    address: "56 Eng Hoon Street, #01-68, Singapore 160056",
    coarseArea: "Tiong Bahru",
    cluster: "tiong_bahru",
    lat: 1.2842,
    lng: 103.8324,
    cuisine: "French Bohemian Cafe & Bistro",
    cuisineCodes: ["french", "cafe", "western", "wine"],
    priceTier: 2,
    rating: 4.5,
    ratingCount: 2150,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      hasDairyFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch", "dinner", "drinks"],
    highlights: ["Artisanal French cheeses", "Croque Marcel", "Charming garden patio"],
    bookingUrl: "https://mercimarcel.com/reservation",
    mapsUrl: openStreetMapVenueUrl(1.2842, 103.8324),
  },
  {
    id: "sg-venue-04",
    name: "Baristart Coffee Tras Street",
    address: "65 Tras Street, Singapore 079004",
    coarseArea: "Tanjong Pagar (CBD)",
    cluster: "central_cbd",
    lat: 1.2778,
    lng: 103.8441,
    cuisine: "Hokkaido Cafe & Desserts",
    cuisineCodes: ["japanese", "cafe", "dessert"],
    priceTier: 2,
    rating: 4.6,
    ratingCount: 1640,
    dietary: {
      hasVegetarianOptions: true,
      hasNutFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch", "dinner"],
    highlights: ["Hokkaido Biei Jersey milk", "Cream puffs", "Obihiro pork bowl"],
    bookingUrl: "https://www.baristartcoffee.sg",
    mapsUrl: openStreetMapVenueUrl(1.2778, 103.8441),
  },
  {
    id: "sg-venue-05",
    name: "Fat Prince",
    address: "48 Peck Seah Street, Singapore 079317",
    coarseArea: "Tanjong Pagar (CBD)",
    cluster: "central_cbd",
    lat: 1.2771,
    lng: 103.8446,
    cuisine: "Modern Middle Eastern & Kebabs",
    cuisineCodes: ["middle_eastern", "mediterranean", "cocktail_bar"],
    priceTier: 3,
    rating: 4.6,
    ratingCount: 1380,
    dietary: {
      hasVegetarianOptions: true,
      hasVeganOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: true,
    },
    supportedMealTypes: ["lunch", "dinner", "drinks"],
    highlights: ["Wagyu beef cheek kebab", "Koktail culture", "Opulent Arabian aesthetics"],
    bookingUrl: "https://www.fatprincesg.com",
    mapsUrl: openStreetMapVenueUrl(1.2771, 103.8446),
  },
  {
    id: "sg-venue-06",
    name: "Papi's Tacos",
    address: "39 Seah Street, Singapore 188395",
    coarseArea: "Bugis / City Hall",
    cluster: "bugis_arab_st",
    lat: 1.2965,
    lng: 103.8548,
    cuisine: "Authentic Mexican Taqueria",
    cuisineCodes: ["mexican", "casual", "cocktails"],
    priceTier: 2,
    rating: 4.5,
    ratingCount: 1820,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["lunch", "dinner", "drinks"],
    highlights: ["Birria beef tacos", "Frozen lime margaritas", "Vibrant street vibe"],
    bookingUrl: "https://papis-tacos.com",
    mapsUrl: openStreetMapVenueUrl(1.2965, 103.8548),
  },
  {
    id: "sg-venue-07",
    name: "The Populus Coffee & Food Co.",
    address: "146 Neil Road, Singapore 088875",
    coarseArea: "Outram / Duxton",
    cluster: "central_cbd",
    lat: 1.2797,
    lng: 103.8415,
    cuisine: "Gastro-Cafe & Specialty Roastery",
    cuisineCodes: ["cafe", "brunch", "western"],
    priceTier: 2,
    rating: 4.6,
    ratingCount: 3100,
    dietary: {
      hasVegetarianOptions: true,
      hasVeganOptions: true,
      hasDairyFreeOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch", "dinner"],
    highlights: ["Populus Scramble", "Roasted grain bowls", "Filter brew bar"],
    bookingUrl: "https://thepopulus.cafe",
    mapsUrl: openStreetMapVenueUrl(1.2797, 103.8415),
  },
  {
    id: "sg-venue-08",
    name: "Fika Swedish Cafe & Bistro",
    address: "257 Beach Road, Singapore 199539",
    coarseArea: "Bugis / Arab Street",
    cluster: "bugis_arab_st",
    lat: 1.3015,
    lng: 103.8601,
    cuisine: "Halal Nordic & Swedish",
    cuisineCodes: ["european", "cafe", "halal"],
    priceTier: 2,
    rating: 4.4,
    ratingCount: 1950,
    dietary: {
      isHalalCertified: true,
      isMuslimOwned: true,
      hasVegetarianOptions: true,
      isPorkFree: true,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch", "dinner"],
    highlights: ["Swedish meatballs with lingonberry", "Smoked salmon crepes", "Halal cozy bistro"],
    bookingUrl: "https://www.fikacafe.com",
    mapsUrl: openStreetMapVenueUrl(1.3015, 103.8601),
  },
  {
    id: "sg-venue-09",
    name: "Super Loco Customs House",
    address: "70 Collyer Quay, #01-04 Customs House, Singapore 049323",
    coarseArea: "Marina Bay / CBD",
    cluster: "central_cbd",
    lat: 1.2829,
    lng: 103.8532,
    cuisine: "Mexican Cocina & Waterfront Bar",
    cuisineCodes: ["mexican", "cocktails", "seafood"],
    priceTier: 3,
    rating: 4.5,
    ratingCount: 1690,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["lunch", "dinner", "drinks"],
    highlights: ["Marina Bay waterfront views", "Baja fish tacos", "Agave tequila list"],
    bookingUrl: "https://www.super-loco.com/customshouse",
    mapsUrl: openStreetMapVenueUrl(1.2829, 103.8532),
  },
  {
    id: "sg-venue-10",
    name: "Candlenut",
    address: "17A Dempsey Road, Singapore 249676",
    coarseArea: "Dempsey Hill",
    cluster: "dempsey",
    lat: 1.3039,
    lng: 103.8085,
    cuisine: "Michelin-Starred Peranakan",
    cuisineCodes: ["peranakan", "local_sg", "michelin"],
    priceTier: 3,
    rating: 4.7,
    ratingCount: 1850,
    dietary: {
      hasVegetarianOptions: true,
      isPorkFree: false,
      hasNutFreeOptions: false,
    },
    supportedMealTypes: ["lunch", "dinner"],
    highlights: ["Michelin-starred Nyonya cuisine", "Ayam Buah Keluak", "Babi Pongteh"],
    bookingUrl: "https://www.comodempsey.sg/restaurant/candlenut",
    mapsUrl: openStreetMapVenueUrl(1.3039, 103.8085),
  },
  {
    id: "sg-venue-11",
    name: "Da Paolo Pizza Bar Holland Village",
    address: "44 Jalan Merah Saga, #01-46, Singapore 278116",
    coarseArea: "Holland Village",
    cluster: "holland_v",
    lat: 1.3120,
    lng: 103.7945,
    cuisine: "Italian Wood-fired Pizza & Wine",
    cuisineCodes: ["italian", "pizza", "wine"],
    priceTier: 2,
    rating: 4.5,
    ratingCount: 1220,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "lunch", "dinner", "drinks"],
    highlights: ["Hand-stretched crispy crust", "Burrata caprese", "Alfresco terrace"],
    bookingUrl: "https://www.dapaolo.com.sg",
    mapsUrl: openStreetMapVenueUrl(1.312, 103.7945),
  },
  {
    id: "sg-venue-12",
    name: "Birds of Paradise Gelato & Cafe",
    address: "53 East Coast Road, Singapore 428771",
    coarseArea: "Katong / Joo Chiat",
    cluster: "joo_chiat",
    lat: 1.3048,
    lng: 103.9038,
    cuisine: "Botanical Gelato & Pastry",
    cuisineCodes: ["dessert", "cafe", "local_sg"],
    priceTier: 1,
    rating: 4.7,
    ratingCount: 3950,
    dietary: {
      hasVegetarianOptions: true,
      hasVeganOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: true,
    },
    supportedMealTypes: ["coffee", "brunch", "drinks"],
    highlights: ["Botanical-infused gelato", "Fresh thyme cones", "Heritage shophouse"],
    bookingUrl: "https://birdsofparadise.sg",
    mapsUrl: openStreetMapVenueUrl(1.3048, 103.9038),
  },
  {
    id: "sg-venue-13",
    name: "Swee Choon Tim Sum Restaurant",
    address: "183/185/187/189/191 Jalan Besar, Singapore 208882",
    coarseArea: "Jalan Besar / Little India",
    cluster: "bugis_arab_st",
    lat: 1.3078,
    lng: 103.8566,
    cuisine: "Hong Kong Dim Sum & Supper",
    cuisineCodes: ["chinese", "dim_sum", "casual"],
    priceTier: 1,
    rating: 4.4,
    ratingCount: 6800,
    dietary: {
      hasVegetarianOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "lunch", "dinner", "drinks"],
    highlights: ["Salted egg yolk lava bao", "Mee Suah Kueh", "Iconic late-night feast"],
    bookingUrl: "https://www.sweechoon.com",
    mapsUrl: openStreetMapVenueUrl(1.3078, 103.8566),
  },
  {
    id: "sg-venue-14",
    name: "Bizen Wagyu Steakhouse",
    address: "68 Orchard Road, #N3-10 Plaza Singapura, Singapore 238839",
    coarseArea: "Dhoby Ghaut / Orchard",
    cluster: "orchard_somerset",
    lat: 1.3007,
    lng: 103.8453,
    cuisine: "Japanese Wagyu Charcoal Grill",
    cuisineCodes: ["japanese", "steakhouse", "western"],
    priceTier: 2,
    rating: 4.6,
    ratingCount: 2200,
    dietary: {
      hasVegetarianOptions: false,
      isPorkFree: false,
      hasNutFreeOptions: true,
    },
    supportedMealTypes: ["lunch", "dinner"],
    highlights: ["Direct-import Okayama A3 Wagyu", "Affordable cuts", "Caramelized onion gravy"],
    bookingUrl: "https://astonssg.com/brands/bizen-wagyu-steakhouse",
    mapsUrl: openStreetMapVenueUrl(1.3007, 103.8453),
  },
  {
    id: "sg-venue-15",
    name: "Atlas Bar",
    address: "600 North Bridge Road, Parkview Square, Singapore 188778",
    coarseArea: "Bugis (Parkview)",
    cluster: "bugis_arab_st",
    lat: 1.3000,
    lng: 103.8576,
    cuisine: "Art Deco European Bar & Dining",
    cuisineCodes: ["cocktail_bar", "european", "drinks"],
    priceTier: 3,
    rating: 4.8,
    ratingCount: 4100,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["dinner", "drinks"],
    highlights: ["1,000+ gin tower", "Gatsby-esque Art Deco hall", "World's 50 Best Bars"],
    bookingUrl: "https://atlasbar.net/reservations",
    mapsUrl: openStreetMapVenueUrl(1.3, 103.8576),
  },
  {
    id: "sg-venue-16",
    name: "Hjh Maimunah Restaurant",
    address: "11 & 15 Jalan Pisang, Singapore 199078",
    coarseArea: "Kampong Glam / Bugis",
    cluster: "bugis_arab_st",
    lat: 1.3023,
    lng: 103.8587,
    cuisine: "Michelin Bib Gourmand Nasi Padang",
    cuisineCodes: ["malay", "indonesian", "halal", "local_sg"],
    priceTier: 1,
    rating: 4.6,
    ratingCount: 3800,
    dietary: {
      isHalalCertified: true,
      isMuslimOwned: true,
      hasVegetarianOptions: true,
      isPorkFree: true,
    },
    supportedMealTypes: ["lunch", "dinner"],
    highlights: ["Michelin Bib Gourmand", "Smoked beef rendang", "Siput sedut lemak"],
    bookingUrl: "https://hjmaimunah.com",
    mapsUrl: openStreetMapVenueUrl(1.3023, 103.8587),
  },
  {
    id: "sg-venue-17",
    name: "OverEasy",
    address: "1 Fullerton Road, #01-06 One Fullerton, Singapore 049213",
    coarseArea: "Raffles Place / Marina Bay",
    cluster: "central_cbd",
    lat: 1.2863,
    lng: 103.8539,
    cuisine: "American Diner & Waterfront Bar",
    cuisineCodes: ["american", "burgers", "cocktails"],
    priceTier: 2,
    rating: 4.4,
    ratingCount: 2300,
    dietary: {
      hasVegetarianOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["lunch", "dinner", "drinks"],
    highlights: ["Marina Bay Sands panorama", "Smash burgers", "Beer can chicken"],
    bookingUrl: "https://www.overeasy.com.sg",
    mapsUrl: openStreetMapVenueUrl(1.2863, 103.8539),
  },
  {
    id: "sg-venue-18",
    name: "PS.Cafe Harding Road",
    address: "28B Harding Road, Singapore 249549",
    coarseArea: "Dempsey Hill",
    cluster: "dempsey",
    lat: 1.3061,
    lng: 103.8098,
    cuisine: "Contemporary Australian-Asian Cafe",
    cuisineCodes: ["cafe", "western", "brunch", "dessert"],
    priceTier: 3,
    rating: 4.5,
    ratingCount: 3400,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch", "dinner", "drinks"],
    highlights: ["Famous truffle shoestring fries", "Lush rainforest glasshouse", "Sticky date pudding"],
    bookingUrl: "https://www.pscafe.com/pscafe-at-harding-road",
    mapsUrl: openStreetMapVenueUrl(1.3061, 103.8098),
  },
  {
    id: "sg-venue-19",
    name: "Neon Pigeon",
    address: "36 Carpenter Street, #01-01, Singapore 059915",
    coarseArea: "Clarke Quay / Chinatown",
    cluster: "clarke_quay",
    lat: 1.2882,
    lng: 103.8471,
    cuisine: "Modern Urban Japanese Izakaya",
    cuisineCodes: ["japanese", "izakaya", "cocktails"],
    priceTier: 3,
    rating: 4.6,
    ratingCount: 1250,
    dietary: {
      hasVegetarianOptions: true,
      hasGlutenFreeOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["dinner", "drinks"],
    highlights: ["Tokyo-gritty izakaya", "Tokyo hummus with edamame", "Japanese craft cocktails"],
    bookingUrl: "https://www.neonpigeonsg.com",
    mapsUrl: openStreetMapVenueUrl(1.2882, 103.8471),
  },
  {
    id: "sg-venue-20",
    name: "Two Men Bagel House Novena",
    address: "103 Irrawaddy Road, #01-04 Royal Square, Singapore 329566",
    coarseArea: "Novena / Balestier",
    cluster: "novena",
    lat: 1.3209,
    lng: 103.8437,
    cuisine: "Hand-rolled New York Bagels",
    cuisineCodes: ["bakery", "cafe", "casual", "brunch"],
    priceTier: 2,
    rating: 4.6,
    ratingCount: 2100,
    dietary: {
      hasVegetarianOptions: true,
      hasVeganOptions: true,
      isPorkFree: false,
    },
    supportedMealTypes: ["brunch", "coffee", "lunch"],
    highlights: ["Hand-rolled fresh bagels", "Lox with dill cream cheese", "Brisk casual counter"],
    bookingUrl: "https://www.twomenbagels.com",
    mapsUrl: openStreetMapVenueUrl(1.3209, 103.8437),
  },
];
